# Segmentation configuration
segmentation:
  ros__parameters:
    use_sim_time: true
    segmentation_model: "yolo11m-seg.pt"
    cam_center: 80
    cam_count: 6
    view_p: 0.30
    view_h: 0.25
    fov_h: 60.0
# Ray Scan configuration
scan:
  ros__parameters:
    max_scan: 20.0
    source_scan: "/scan"
# Odom configuration
odom:
  ros__parameters:
    source_odom: "/odom"
# Autonomous Exploration configuration
autonomous_exploration:
  ros__parameters:
    target_vel : "cmd_vel"
    lookahead_distance : 0.24
    speed : 0.15
    expansion_size : 20
    target_error : 0.3
    robot_r : 1.5