lookahead_distance : 0.24 #front look distance
speed : 0.15 #maximum speed (reduced for safety)
expansion_size : 20 #wall expansion coefficient (increased safety margin)
target_error : 0.3 #margin of error to target
robot_r : 1.6 #robot distance for local safety (increased safety)
replanning_threshold : 1.5 #threshold for dynamic replanning
stuck_detection_time : 8.0 #time to detect if robot is stuck (increased)
stuck_distance_threshold : 0.01 #minimum distance to consider stuck (more sensitive)
target_revisit_timeout : 30.0 #seconds before allowing revisit to same target
min_target_distance_multiplier : 4 #minimum distance = target_error * this value
frontier_size_bonus_factor : 10.0 #frontier size bonus normalization factor
safe_exploration_max_distance : 3.0 #maximum safe exploration movement distance
