hazard_lookup = {
    # Kendaraan - Hazard Tinggi (7–10)
    "car": 9,
    "bus": 9,
    "truck": 9,
    "motorcycle": 8,
    "bicycle": 7,
    "train": 10,
    "airplane": 10,
    "boat": 8,
    "fire hydrant": 9,

    # Makhluk hidup - Hazard Sedang (4–6)
    "person": 6,
    "dog": 5,
    "cat": 4,
    "horse": 6,
    "sheep": 5,
    "cow": 5,
    "bird": 4,
    "elephant": 6,
    "bear": 6,
    "zebra": 5,
    "giraffe": 5,

    # Lain-lain - Hazard Rendah (1–3)
    "traffic light": 3,
    "stop sign": 3,
    "parking meter": 3,
    "bench": 3,
    "backpack": 2,
    "umbrella": 3,
    "handbag": 2,
    "tie": 2,
    "suitcase": 3,
    "frisbee": 2,
    "skateboard": 2,
    "sports ball": 3,
    "kite": 2,
    "bottle": 2,
    "cup": 2,
    "fork": 2,
    "knife": 3,
    "spoon": 2,
    "bowl": 2,
    "banana": 2,
    "apple": 2,
    "sandwich": 2,
    "orange": 2,
    "broccoli": 2,
    "carrot": 2,
    "hot dog": 2,
    "pizza": 2,
    "donut": 2,
    "cake": 2,
    "chair": 3,
    "couch": 3,
    "potted plant": 3,
    "bed": 3,
    "dining table": 3,
    "tv": 2,
    "laptop": 2,
    "mouse": 2,
    "remote": 2,
    "keyboard": 2,
    "cell phone": 2,
    "microwave": 2,
    "oven": 2,
    "toaster": 2,
    "sink": 3,
    "refrigerator": 3,
    "book": 2,
    "clock": 2,
    "vase": 2,
    "scissors": 2,
    "teddy bear": 2,
    "hair drier": 2,
    "toothbrush": 2
}
